apiVersion: v1
kind: ConfigMap
metadata:
  name: hasher-config
  namespace: default
  labels:
    app: nginx
data:
  NAMESPACE: "default"
  nginx: |
    PID_NAME=nginx
    MOUNT_PATH=etc/nginx/nginx.conf
  php: |
    PID_NAME=php
    MOUNT_PATH=etc/deb.conf