kind: PersistentVolume
apiVersion: v1
metadata:
  name: hasher-persistent-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/persistent-volume"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hasher-persistent-volumeclaim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
