apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: hasher
      shareProcessNamespace: true
      containers:
        - name: nginx
          image: nginx:latest
        - name: hasher
          image: hasher:latest
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
          stdin: true
          tty: true
          imagePullPolicy: Never
          envFrom:
            - secretRef:
                name: postgres-secret
          command: [ "sh","-c","pid=$(pidof -s $PID_NAME);echo $pid; ./sha256sum -d ../proc/$pid/root/etc/nginx/nginx.conf;"]
          env:
            - name: PID_NAME
              value: "nginx"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name