apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullstack-postgres
  labels:
    app: fullstack-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fullstack-postgres
      tier: postgres
  template:
    metadata:
      labels:
        app: fullstack-postgres
        tier: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh","-c","sleep 20 && PGPASSWORD=$POSTGRES_PASSWORD psql -w -d $POSTGRES_DB -U $POSTGRES_USER -c 
                'CREATE TABLE files
                (
                    id          BIGSERIAL PRIMARY KEY,
                    file_name   VARCHAR,
                    file_path   TEXT,
                    hash_value  VARCHAR,
                    hash_type   VARCHAR,
                    deleted     BOOLEAN DEFAULT FALSE,
                
                    CONSTRAINT files_unique UNIQUE (file_path, hash_type)
                );'"]
          envFrom:
            - secretRef:
                name: postgres-secret

          ports:
            - containerPort: 5432
              name: postgres
