apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: tcpdump-webhook
webhooks:
  - name: tcpdump-webhook.default.svc.cluster.local
    failurePolicy: Fail
    clientConfig:
      service:
        name: tcpdump-webhook
        namespace: default
        path: "/mutate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURkRENDQWx5Z0F3SUJBZ0lVWTlIdVNIbnJ4ckw0MWtuRzFUWGtuL1J5bFUwd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1VqRUxNQWtHQTFVRUJoTUNRVlV4RURBT0JnTlZCQWdUQjBWNFlXMXdiR1V4RWpBUUJnTlZCQWNUQ1UxbApiR0p2ZFhKdVpURVFNQTRHQTFVRUNoTUhSWGhoYlhCc1pURUxNQWtHQTFVRUN4TUNRMEV3SGhjTk1qSXdOakl6Ck1UWXdPVEF3V2hjTk1qY3dOakl5TVRZd09UQXdXakJTTVFzd0NRWURWUVFHRXdKQlZURVFNQTRHQTFVRUNCTUgKUlhoaGJYQnNaVEVTTUJBR0ExVUVCeE1KVFdWc1ltOTFjbTVsTVJBd0RnWURWUVFLRXdkRmVHRnRjR3hsTVFzdwpDUVlEVlFRTEV3SkRRVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMQklOQWZZCnUwYnZ4dWV2QjE5dmlyR09MbzRKdXJ6blp1UEU4cW1zTDlxNE1Pb0gxRExHZi82bDFnZEJTRUx3T0szRUNwREIKdm9sajk0VktLM245c2JnN3lza2ZubW9HdURqNUJMYjVtMXA5U3FpT1FaandKeWYvN1l4OUxuTFdqZ0psUm9ScApxY1FhNWZQT1VzNkRCUTQ0Y3NmRWVRVjB2blVhOXdFM2kxOE1XOFhSdDF0Vmg0MVBrMnZERGlFa3hWdGVHLzV2ClpJK0phS29LWUVnZG9kRHh6OWRUUzVPSlNIQTdSNld2QlYrcnI2SUU1OXVqem1IQ0psYTYza2I2cXE5ZFFobEEKSk94L2RIeXhUNmhMYVA1cFZKZVU0T0ZnNWFFc1ozemRSdGdhKzIrdy9TK2ZJeEZibklsWFdWQ3p1aGU0U0NDUApvWHUrM2NCYTNaUjArRHNDQXdFQUFhTkNNRUF3RGdZRFZSMFBBUUgvQkFRREFnRUdNQThHQTFVZEV3RUIvd1FGCk1BTUJBZjh3SFFZRFZSME9CQllFRkFUUFlxdXg0QUdDaDB0YlhDamJ4bmtGNnZmU01BMEdDU3FHU0liM0RRRUIKQ3dVQUE0SUJBUUNNTHNGWFE1TzM1SHpsSGM5MmJrSTJhbmRwUFlmNURTQkZWY2tYWHZZTy9Kb0hQNFFNNEw0ZQpHTHAxT2dUUUZKUlpTN1FycTlsWXpicmhhN0VIMnMzdmZpR1dPNmlaQjlZRndUT0QrTlM2MnQ1ZTB6aCtlVlNWCkhDS2xqbE9pckZhUis3QTNZa1o3R1RwR1pQQ3pBWkJWc3BlSFpWNng3b1ZMT09sejJhQVhCd2JMQlgzNktxWVQKOFlvUXV3TmxwZExSRUg1elg0Um1aWXVEUzhrU2FRQ202L0RCNGg0ZTNqM0JaL25wcHZqOWxSMkwwblF1K3NPTApndENIT1d2eXpDRlBpeEtmNjNabSt4WTFSR2F3NE4rVU9mVW9DQnlrY0pwaEVMSktKWkh0OTZCU0d5NXBNR0NNCjBWNmtNZ0VHNnRJZTdoTjhKdUw4Wm1jajNmVmFjQ0pSCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 5