---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ssl-tcpdump-webhook
  namespace: default
data:
  server.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVCekNDQXUrZ0F3SUJBZ0lVWEFJckVGZnhLbWdSczZ5MFlRalBQSFB0eVRJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1VqRUxNQWtHQTFVRUJoTUNRVlV4RURBT0JnTlZCQWdUQjBWNFlXMXdiR1V4RWpBUUJnTlZCQWNUQ1UxbApiR0p2ZFhKdVpURVFNQTRHQTFVRUNoTUhSWGhoYlhCc1pURUxNQWtHQTFVRUN4TUNRMEV3SGhjTk1qSXdOakl6Ck1UWXdPVEF3V2hjTk5ESXdOakU0TVRZd09UQXdXakJTTVFzd0NRWURWUVFHRXdKQlZURVFNQTRHQTFVRUNCTUgKUlhoaGJYQnNaVEVTTUJBR0ExVUVCeE1KVFdWc1ltOTFjbTVsTVJBd0RnWURWUVFLRXdkRmVHRnRjR3hsTVFzdwpDUVlEVlFRTEV3SkRRVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMNnZTSThqCnQ0WEdUR2RLWTlydHNaWSsxdWtXeU5PNnV5U2dqSDNhcFNQd1JESnFxeVpUTkZxR28rWlIyaUE4ejY2QmthZmcKTFdvMjNHT3ZQN3IzTzFmeWZrY05mV1daT0J1VDJvU3dkR1pmeHJoeVNCN09CRjhnUTg0N0tDU0p5UWVqVUNaWQpQbWp0YUZJZ2gwR3k1ODh0NXRXckNsNFRQYVNtZ1ZUWWM3TFhjY1JDUVlnMjR0L1lPbU9NQk5GUEs2WGdndWdOCjM1UjZTYm9JYkVnMXNpZldjUXpDcHFnSDJZU1h3bjRTUlNKVUI4WEw3T2doMDVrYjJQZG5HRHovSnVpT0tQYkcKOGdsRWVFeGVkRkU4L0pMcndHYmhHNDgrV01PR3NJcUJMQnRvb2Z1RElaOWszU1hMbmZwSkRjeFozWVJWTXJ6egpvYWVDQ2FFTUJUT0lRS0VDQXdFQUFhT0IxRENCMFRBT0JnTlZIUThCQWY4RUJBTUNCYUF3SFFZRFZSMGxCQll3CkZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNQXdHQTFVZEV3RUIvd1FDTUFBd0hRWURWUjBPQkJZRUZPK1kKbWE5ek1vWUlhL1RzSVgxRFFDRTNLalEyTUhNR0ExVWRFUVJzTUdxQ0QzUmpjR1IxYlhBdGQyVmlhRzl2YTRJcApkR053WkhWdGNDMTNaV0pvYjI5ckxtUmxabUYxYkhRdWMzWmpMbU5zZFhOMFpYSXViRzlqWVd5Q0czUmpjR1IxCmJYQXRkMlZpYUc5dmF5NWtaV1poZFd4MExuTjJZNElKYkc5allXeG9iM04waHdSL0FBQUJNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBVkdPcVNLRFFrOFZ3RmwzSE9pd3dFdG5laUVBK21INkdpWTkyWDFsc1h2TnFVeGtUUApBd00zaCtvZTdxUnV5Vzk0YnVzNWg1WTNRZis4VTBDNTBHbDRyMDBQazE0TUFEc3o1bFNIOGhQQUs3bkRNNys4CmdVdjBDM2xGZXVlbnlvcWlVZlNzcDNQOTFMTjYySzJCRERTL1pFNVoyUzZQL0pwQ1FKWkVZeHllaUJVYlVRc2sKTDFFSHpVYkc4NlVXSlpRemllYkJqUk0zK2NITXFRblNtU2J6VEZpMlBZN1F2emRwaE1ZNGZXdE1JcG9aQkduNApPY3VUTEJoVXFwTEdzZ3h2OHdTaEhtOEVYeWFLK0VrN2RUQUJidnFFWm43Y1VLcU14c0NuMThjcHUxMmh5QWdTCm9VV1ZKc3hsNmE1eVJHZlpmVy9QMHJIclJKN0ZxY0hDNG5jZwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  server.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBdnE5SWp5TzNoY1pNWjBwajJ1MnhsajdXNlJiSTA3cTdKS0NNZmRxbEkvQkVNbXFyCkpsTTBXb2FqNWxIYUlEelByb0dScCtBdGFqYmNZNjgvdXZjN1YvSitSdzE5WlprNEc1UGFoTEIwWmwvR3VISkkKSHM0RVh5QkR6anNvSkluSkI2TlFKbGcrYU8xb1VpQ0hRYkxuenkzbTFhc0tYaE05cEthQlZOaHpzdGR4eEVKQgppRGJpMzlnNlk0d0UwVThycGVDQzZBM2ZsSHBKdWdoc1NEV3lKOVp4RE1LbXFBZlpoSmZDZmhKRklsUUh4Y3ZzCjZDSFRtUnZZOTJjWVBQOG02STRvOXNieUNVUjRURjUwVVR6OGt1dkFadUViano1WXc0YXdpb0VzRzJpaCs0TWgKbjJUZEpjdWQra2tOekZuZGhGVXl2UE9ocDRJSm9Rd0ZNNGhBb1FJREFRQUJBb0lCQUdkYlZVWVpBd25rd1ZjZgpjRjZqaGlXOUsvb3QybTlCZ056S2xUeEdma3FybWh1RnkvMDdEbDZmS2tuV1JoaEJQZ1VGd0RDeGg0eFI3a1d1CklTb3poaHdXbWJIanN2dVdBRjZhVnRDallJUjVGNXEwZnprTFREMVBuTkUxS1g0Y25UV2hwUGtUemNoTUhzYWQKVVJNZ2FSdlljbzJRWjA4MHVLMzlmbzdCd0h6SDhSdktjOS9ZSzdpbEJoeXh3Sk1CdUU1bkVHaEs5MjVzdStTaQpiZmlHQ0REZFZoTVZ6OFZYVUNiczMramNZNitVNWJUd0t4R3M5RmJySndKR3VJeDhMcHd2L091YXl4aVZDaEdNCmx0am1kMlhlaHp1RmxsUEMvaFVOWDhHYlFCSFY1dUw4dnBOd1RxbnRiQjN4V0ZYYjVlU2h0eFU5NG5PT2x4RWwKcDFwMmxoRUNnWUVBNEZuN21FTXlsTU9ITkJtZ1Q4bW5tTi8xT0ovRzFibkNKZU9nemp5dWkybjBxYnVmK1Q4VApGNkVoY0U2aFJtRStRb0lUd3BGTjVJTkJicndpbXdQQk1OVGZlNWE3aHNhUHZ3V0ROZGwwMFNTWitkTUpoSFJ0Cm9RSGVaKzh2RlBzb2luQzZhSzh1dkU4SEYxRjF2K3k5UDV1MG1oR2NhOFdpQUJxem4yVWRjTTBDZ1lFQTJaVjkKYlROUkxJQVgvSEI2SFdQd3JwalBjZnNkSHFTQXU3NGxIL3IzbHpyeTI5RVJYR2dlbUdmWENyK0syVFZELzdKaQpnOUZDdHJIVVNqV2lTTWVhWmt1ZG1xSTlRVGpHTjNlZ1BhRGZKanVJK2ozQ3VKV0c1dGdVdkxLdFhUN2RPOTA2Cjc0eHhzb0VVb2wzQVBhRGE1QTNOUWZsbkhFWXJTTFQ1V0tPV3Z5VUNnWUVBdURvcjE4U1diSUtESzgwL1QwV1EKVW9EVnBVSE96UUpVNHpnZ2ZEcG9PaU12dlpGTXRDZVBUZ0FLcldaa0dKOFJ1UnVIam1ZelNFcGdHTVoweEVZNQpCaGhIeS96aTBMR01xSmVtUHpucUt6T2JIUUttOWhXRlVJbHdVSGlnZU9JbFVFbHhTVFZSYzJDUnVod3lUUC9pCkI3R2NoRWVoNHYzUEliYkxlVUJYQktFQ2dZQS9xaVlSRmJyaXNuaFNQUGIrTW9meURuUmtmWDEvd2RLSkhKSHcKVVphd2dXY2VPb1pCNjVWSU10b1JJd3FWazZoWjRQQkNjYkI3bEh6eFdkQXFTMzA2QVZZVU1QU0xhUGxXc1lJSgpobERFOXhhVllnemZ4YUM3V3U1MmFER2gzd3NNd1NiRmdPcWp1SEU1TVFWWEF3SUpTS0NPZFZOZVNvblB0R1JoCk16eWdvUUtCZ1FESUNyeVlNSEdVTUpHMXBaMDdJUVJsVTZELzRjbE5uNWhWTzN6Y1NlTGpGVnpvWXZwWHBrTGoKYUtBdUhHRlBHVFB4RUFTSU12cU5xT2prbGhjMGZJNmw4RUxzTDdKemo5aHo1RmRpcXNGT3lSUkhoeHFFVzgvSQpSdEdhZnQvSGxTZ1pLc1NON0JEclBjVytrdHl4eUNSMW5WRkRFUHRsbjZxTWtLbVlxWmFFWUE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcpdump-webhook
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      component: tcpdump-webhook
  template:
    metadata:
      labels:
        component: tcpdump-webhook
    spec:
      containers:
        - name: tcpdump-ws
          image: webhook:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8443
          volumeMounts:
            - name: ssl-tcpdump-webhook
              mountPath: /ssl
      volumes:
        - name: ssl-tcpdump-webhook
          configMap:
            name: ssl-tcpdump-webhook
---

kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: tcpdump-webhook
spec:
  selector:
    component: tcpdump-webhook
  ports:
    - name: http
      port: 443
      targetPort: 8443